//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartParking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BoardParkInfo
    {
        public int BoardParkInfoID { get; set; }
        public Nullable<int> ParkingSlotID { get; set; }
        public string pin { get; set; }
        public string gpio { get; set; }
        public string value { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
    
        public virtual ParkingSlot ParkingSlot { get; set; }
    }
}
