//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartParking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParkingSlot
    {
        public ParkingSlot()
        {
            this.BoardParkInfoes = new HashSet<BoardParkInfo>();
        }
    
        public int ParkingSlotID { get; set; }
        public int OwnerID { get; set; }
        public string ParkingSlotAddress { get; set; }
        public string SlotNumber { get; set; }
        public Nullable<System.DateTime> AvailableStartDate { get; set; }
        public Nullable<System.DateTime> AvailableEndDate { get; set; }
        public Nullable<bool> value { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<System.TimeSpan> EndTime { get; set; }
    
        public virtual ICollection<BoardParkInfo> BoardParkInfoes { get; set; }
        public virtual Owner Owner { get; set; }
    }
}
