//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartParking.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SmartParkingEntities1 : DbContext
    {
        public SmartParkingEntities1()
            : base("name=SmartParkingEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BoardParkInfo> BoardParkInfoes { get; set; }
        public virtual DbSet<Owner> Owners { get; set; }
        public virtual DbSet<ParkingSlot> ParkingSlots { get; set; }
    }
}
